# How to copy a variable in python

Being a heavy user of Matlab, I didn't struggle so much for most of python commands at first. 
They were sharing the similar grammer and all I had to do was translating the code written in Matlab into the python language. However, I met a serious problem (this is not a hard one to debug, but I bet most of python newbies would encounter this problem anytime soon). 



In [3]:
import numpy as np


# Define a varible
x = [100, 50, 70, 100, 60, 50, 20, 80]

# Make a copy of x and make change in x1
x1 = x
x1 = x1 + np.random.rand(1,8)


# Compare the difference between x1 and x
print(x1-x)
print(x)
print(x1)


[[0.28339781 0.77733302 0.8279953  0.31488944 0.46158291 0.48909504
  0.76566248 0.04978844]]
[100, 50, 70, 100, 60, 50, 20, 80]
[[100.28339781  50.77733302  70.8279953  100.31488944  60.46158291
   50.48909504  20.76566248  80.04978844]]


Note that there's absolutely no problem with the code. 

Problem occured when I tried to make a copy of a variable and make change on that copied variable:

In [4]:
# Define a varible
x = np.array([100, 50, 70, 100, 60, 50, 20, 80])

# Make a copy of x and make change in x1
x1 = x
x1[0] = 50


# Compare the difference between x1 and x
print(x1-x)
print(x)
print(x1)

[0 0 0 0 0 0 0 0]
[ 50  50  70 100  60  50  20  80]
[ 50  50  70 100  60  50  20  80]


In [5]:
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))